# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15.1

# --- Build stage: compile sabctools from source ---
FROM ghcr.io/daemonless/base:${BASE_VERSION} AS builder
RUN pkg update && \
    pkg install -y FreeBSD-clang FreeBSD-clang-dev FreeBSD-clibs-dev python311 py311-pip py311-setuptools && \
    pip-3.11 install --target=/tmp/sabctools-build --no-cache-dir sabctools && \
    chmod -R a+rX /tmp/sabctools-build/sabctools* && \
    pkg remove -y FreeBSD-clang FreeBSD-clang-dev FreeBSD-clibs-dev py311-pip py311-setuptools && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# --- Final stage ---
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="python311 py311-pip py311-setuptools py311-sqlite3 py311-cryptography py311-feedparser py311-configobj py311-cherrypy py311-portend py311-chardet py311-pysocks py311-guessit py311-puremagic py311-rarfile py311-apprise par2cmdline-turbo unrar 7-zip ca_root_nss"
ARG UPSTREAM_URL="https://api.github.com/repos/sabnzbd/sabnzbd/releases/latest"
ARG UPSTREAM_JQ=".tag_name"
ARG HEALTHCHECK_ENDPOINT="http://localhost:8080/api?mode=version"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="SABnzbd" \
      org.opencontainers.image.description="Free and easy binary newsreader that automates the downloading and processing of Usenet content." \
      org.opencontainers.image.source="https://github.com/daemonless/sabnzbd" \
      org.opencontainers.image.url="https://sabnzbd.org/" \
      org.opencontainers.image.documentation="https://sabnzbd.org/wiki/" \
      org.opencontainers.image.licenses="GPL-2.0-or-later" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Downloaders" \
      io.daemonless.port="8080" \
      io.daemonless.volumes="/config,/downloads" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.packages="${PACKAGES}"

# Install dependencies
RUN pkg update && \
    pkg install -y \
    ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Copy compiled sabctools from builder
COPY --from=builder /tmp/sabctools-build/ /usr/local/lib/python3.11/site-packages/

# Download and install SABnzbd from GitHub
RUN mkdir -p /app/sabnzbd && \
    chmod 755 /app && \
    SABNZBD_VERSION=$(fetch -qo - "${UPSTREAM_URL}" | jq -r "${UPSTREAM_JQ}") && \
    echo "Downloading SABnzbd ${SABNZBD_VERSION}" && \
    fetch -qo /tmp/sabnzbd.tar.gz "https://github.com/sabnzbd/sabnzbd/releases/download/${SABNZBD_VERSION}/SABnzbd-${SABNZBD_VERSION}-src.tar.gz" && \
    LANG=C.UTF-8 tar xzf /tmp/sabnzbd.tar.gz -C /app/sabnzbd --strip-components=1 && \
    test -f /app/sabnzbd/SABnzbd.py && \
    chmod -R o+rX /app/sabnzbd && \
    printf "UpdateMethod=docker\nPackageVersion=%s\nPackageAuthor=[daemonless](https://github.com/daemonless/daemonless)\n" "$SABNZBD_VERSION" > /app/sabnzbd/package_info && \
    echo "$SABNZBD_VERSION" > /app/version && \
    rm -f /tmp/sabnzbd.tar.gz

# Create directories
RUN mkdir -p /config /downloads/complete /downloads/incomplete && \
    chown -R bsd:bsd /app/sabnzbd /config /downloads

# Copy service definition and init scripts
COPY root/ /

# Make scripts executable
RUN chmod +x /etc/services.d/sabnzbd/run /etc/cont-init.d/* 2>/dev/null || true

# --- Expose (Injected by Generator) ---
EXPOSE 8080

# --- Volumes (Injected by Generator) ---
VOLUME /config /downloads