icon: ':material-download-network:'
cit:
  mode: screenshot
  port: 8080
  health: /api?mode=version

build:
  variants:
    - tag: latest
      containerfile: Containerfile
      default: true
    - tag: pkg
      containerfile: Containerfile.pkg
    - tag: pkg-latest
      containerfile: Containerfile.pkg
      args:
        BASE_VERSION: "15-latest"
